### ISSUE TITLE
CommonLogHolder classname interference

### ISSUE THREAD

**Issue by tranhungt** [opentable/otj-logging#26]
com.opentable.logging.CommonLogHolder class exists in both otj-logging and otj-logging-core. We use this in spring-logging project, and when CommonLogHolder is called to `setServiceType` it fails because it cannot find the method, because com.opentable.logging.CommonLogHolder was loaded from otj-logging-core instead of the intended otj-logging.

otj-logging version 2.0.1
otj-logging-core version 1.10.1

**Comment by tranhungt** [comment]
Was otj-logging meant to replace otj-logging-core?

**Comment by pennello** [comment]
cc @stevenschlansker 

Note the major versions of the two conflicting artifacts.  I think the issue here is that we must have moved the class from core to `otj-logging` when we went from Guice to Spring.

**Comment by stevenschlansker** [comment]
Yes, `otj-logging-core` is dead, just prune it from anywhere that still references it.
